#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TOTAL_STAGES=5

banner "Deploy huddleup to Vercel"

# ── Stage 1: create the GitHub repo ────────────────────────────────────────
stage "GitHub: create the repo"
say "This project has no git remote yet, so we need a GitHub repo to push to."
open_url "https://github.com/new"
step "Name it (e.g. huddleup). Public or private, your call."
step "Leave 'Add a README', '.gitignore', and 'license' UNCHECKED — this repo already has commits, and GitHub will refuse to push if the histories don't match."
step "Click 'Create repository'. GitHub then shows a remote URL — copy the HTTPS one (https://github.com/you/huddleup.git)."
ask GITHUB_REMOTE_URL "Paste the repo URL:"

# ── Stage 2: commit and push ────────────────────────────────────────────────
stage "Push your code to GitHub"
say "Committing your current work and pushing it to the repo you just made."
if [[ -n "$(git status --porcelain)" ]]; then
  git status --short
  if confirm "Commit all of the above now?"; then
    git add -A
    git commit -m "Add auth, onboarding, dashboard, and activity log"
  else
    warn "Skipping commit — push below may fail or push stale code until you commit yourself."
  fi
else
  note "Nothing to commit — working tree is already clean."
fi
if git remote get-url origin >/dev/null 2>&1; then
  git remote set-url origin "$GITHUB_REMOTE_URL"
else
  git remote add origin "$GITHUB_REMOTE_URL"
fi
git branch -M main
git push -u origin main
note "Pushed. Refresh the GitHub page to see your code."

# ── Stage 3: import into Vercel ─────────────────────────────────────────────
stage "Vercel: import the project"
say "Now connect that GitHub repo to Vercel."
open_url "https://vercel.com/new"
step "Sign in with GitHub if prompted, and authorize Vercel to access your repos."
step "Find your new repo (e.g. huddleup) in the list and click 'Import'."
step "Framework Preset should auto-detect 'Next.js' — leave the build settings as default."
note "Don't click Deploy yet — add the env vars in the next stage first, so the first build doesn't crash on missing Supabase config."
pause "Press Enter once you're on the 'Configure Project' screen"

# ── Stage 4: environment variables ──────────────────────────────────────────
stage "Vercel: add environment variables"
SUPABASE_URL_VAL=$(_existing NEXT_PUBLIC_SUPABASE_URL || true)
SUPABASE_ANON_VAL=$(_existing NEXT_PUBLIC_SUPABASE_ANON_KEY || true)
if [[ -z "$SUPABASE_URL_VAL" || -z "$SUPABASE_ANON_VAL" ]]; then
  warn "Couldn't find both values in $ENV_FILE — enter them manually below."
  ask SUPABASE_URL_VAL "NEXT_PUBLIC_SUPABASE_URL:"
  ask SUPABASE_ANON_VAL "NEXT_PUBLIC_SUPABASE_ANON_KEY:"
fi
say "In the 'Environment Variables' section of the import screen, add these two (same values as your local $ENV_FILE):"
step "NEXT_PUBLIC_SUPABASE_URL = $SUPABASE_URL_VAL"
step "NEXT_PUBLIC_SUPABASE_ANON_KEY = $SUPABASE_ANON_VAL"
step "Click 'Deploy'."
say "Vercel will build and deploy — this takes a minute or two."
pause "Press Enter once Vercel shows the 'Congratulations' screen with your live URL"

# ── Stage 5: verify + fix Supabase auth redirect ────────────────────────────
stage "Verify the live app"
ask DEPLOY_URL "Paste your Vercel deployment URL (e.g. https://huddleup-xyz.vercel.app):"
warn "Supabase blocks auth redirects from URLs it doesn't know about — add this one now or signup will silently fail on the live site."
open_url "https://supabase.com/dashboard/project/_/auth/url-configuration"
step "Set 'Site URL' to your Vercel URL: $DEPLOY_URL"
step "Under 'Redirect URLs', add: $DEPLOY_URL/**"
step "Click 'Save'."
open_url "$DEPLOY_URL"
step "On the live site, run through signup → onboarding → dashboard → log an activity, same as you tested locally."
note "If a build fails, check the Vercel deployment logs — most first-deploy failures are a missing/mistyped env var."
# ──────────────────────────────────────────────────────────────────────────

finish
